/* =========================================================================
   ARK: Survival Ascended — Server Config Creator
   Option database. Every option:
     k  = INI key
     f  = file: 'gus' (GameUserSettings.ini) or 'game' (Game.ini)
     s  = INI section (defaults: gus -> ServerSettings, game -> /script/shootergame.shootergamemode)
     t  = type: 'bool' | 'float' | 'int' | 'str' | 'text' (one Key=Line per line) | 'raw' (lines copied verbatim)
     d  = default value
     c  = category id
     n  = friendly name
     h  = plain-English help text
     mn/mx/st = slider range for numbers (optional)
     ph = placeholder text (optional)
     note = extra warning / tip shown in small print (optional)
     grp/gi = stat-group id and index (for the 12-stat tables)
   ========================================================================= */

const STAT_NAMES = ['Health', 'Stamina', 'Torpidity', 'Oxygen', 'Food', 'Water', 'Temperature', 'Weight', 'Melee Damage', 'Movement Speed', 'Fortitude', 'Crafting Speed'];

const CATEGORIES = [
  { id: 'basics',      icon: 'server', name: 'Server Basics',          desc: 'Name, passwords, ports and the message players see when they join.' },
  { id: 'rules',       icon: 'sliders', name: 'Game Rules',             desc: 'PvE or PvP, difficulty, tribes, alliances and general rules.' },
  { id: 'rates',       icon: 'bolt', name: 'Rates & Multipliers',    desc: 'XP, harvesting, taming and other core speed settings. Higher = faster/more.' },
  { id: 'stats',       icon: 'dumbbell', name: 'Players & Dino Stats',   desc: 'Damage, resistance, food/water drain and per-level stat gains.' },
  { id: 'breeding',    icon: 'egg', name: 'Breeding & Imprinting',  desc: 'Mating, egg hatching, baby raising and imprinting.' },
  { id: 'dinos',       icon: 'dino', name: 'Wild & Tamed Dinos',     desc: 'Tame limits, dino decay, cryopods and taming rules.' },
  { id: 'structures',  icon: 'blocks', name: 'Building & Structures',  desc: 'Building limits, structure decay, pickup rules and platform saddles.' },
  { id: 'items',       icon: 'pack', name: 'Items & Loot',           desc: 'Stack sizes, spoiling, loot crates, fishing and custom recipes.' },
  { id: 'environment', icon: 'globe', name: 'World & Environment',    desc: 'Day/night cycle, weather, crops and resource respawning.' },
  { id: 'pvp',         icon: 'swords', name: 'PvP Settings',           desc: 'Offline raid protection, turret limits, respawn timers and C4 rules.' },
  { id: 'transfers',   icon: 'plane', name: 'Clusters & Transfers',   desc: 'Uploading/downloading characters, dinos and items between servers.' },
  { id: 'chat',        icon: 'chat', name: 'Chat & Notifications',   desc: 'Voice chat, join/leave messages.' },
  { id: 'hud',         icon: 'eye', name: 'HUD & Visuals',          desc: 'Crosshair, map location, damage text, third person and gamma.' },
  { id: 'admin',       icon: 'shield', name: 'Admin, Saves & Logs',    desc: 'Admin password, RCON, auto-saves, idle kick and logging.' },
  { id: 'engrams',     icon: 'book', name: 'Engrams & Leveling',     desc: 'Engram unlocks, level caps, XP ramps and respec rules.' },
  { id: 'advanced',    icon: 'dna', name: 'Advanced Overrides',     desc: 'Power-user settings: spawn overrides, per-dino multipliers, crafting costs. Each line is one entry.' },
  { id: 'custom',      icon: 'filetext', name: 'Custom / Extra Lines',   desc: 'Anything else. Lines here are added to the files exactly as written. Imported settings this tool does not know also land here, so nothing gets lost.' },
  { id: 'mods',        icon: 'puzzle', name: 'Mods',                   desc: 'Pick mods from the CurseForge catalog. Selected mods are added to your start command automatically, and mods with known settings get friendly config controls right here.' },
  { id: 'launch',      icon: 'rocket', name: 'Launch Options',         desc: 'Map, player slots, mods, crossplay and the start-up command for your server.' },
  { id: 'setup',       icon: 'server', name: 'Set Up Local Server',    desc: 'Install an ARK: Survival Ascended dedicated server on this PC, write your generated files into it, and start it.' },
  { id: 'deploy',      icon: 'upload', name: 'Deploy',                 desc: 'Connect your host — Nitrado, a Pterodactyl panel (Legion Hosting and others) or a self-hosted server — to read its current config and deploy changes directly.' },
];

const OPTIONS = [

  /* ================= SERVER BASICS ================= */
  { k: 'SessionName', f: 'gus', s: 'SessionSettings', t: 'str', d: '', c: 'basics', n: 'Server Name', ph: 'My Awesome ARK Server',
    h: 'The name of your server as it appears in the server browser.' },
  { k: 'Port', f: 'gus', s: 'SessionSettings', t: 'int', d: 7777, c: 'basics', n: 'Game Port',
    h: 'The UDP port players connect through. Remember to open (forward) this port and the one above it (e.g. 7777 + 7778) in your router/firewall.' },
  { k: 'MultiHome', f: 'gus', s: 'SessionSettings', t: 'str', d: '', c: 'basics', ph: 'e.g. 192.168.1.10',
    n: 'Bind to IP Address (MultiHome)', h: 'Only needed on machines with several network cards / IP addresses. Leave empty unless your host tells you to set it.' },
  { k: 'ServerPassword', f: 'gus', t: 'str', d: '', c: 'basics', n: 'Join Password', ph: 'leave empty = public server',
    h: 'If set, players must enter this password to join. Leave empty for a public server.' },
  { k: 'ServerAdminPassword', f: 'gus', t: 'str', d: '', c: 'basics', n: 'Admin Password', ph: 'choose a strong password',
    h: 'The password for admin access (cheat commands, RCON). Never share it with normal players.' },
  { k: 'Message', f: 'gus', s: 'MessageOfTheDay', t: 'str', d: '', c: 'basics', n: 'Message of the Day', ph: 'Welcome to our server! Type \\n for a new line.',
    h: 'A welcome message shown to players when they join. Write \\n (backslash + n) where you want a line break.' },
  { k: 'Duration', f: 'gus', s: 'MessageOfTheDay', t: 'int', d: 20, c: 'basics', n: 'Message Duration (seconds)',
    h: 'How many seconds the Message of the Day stays on screen.' },

  /* ================= GAME RULES ================= */
  { k: 'ServerPVE', f: 'gus', t: 'bool', d: false, c: 'rules', n: 'PvE Mode',
    h: 'ON = players cannot damage each other or each other\'s buildings (Player vs Environment). OFF = PvP server.' },
  { k: 'ServerHardcore', f: 'gus', t: 'bool', d: false, c: 'rules', n: 'Hardcore Mode',
    h: 'ON = when a player dies, their character is wiped back to level 1. Very punishing — most servers leave this off.' },
  { k: 'DifficultyOffset', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 1, st: 0.01, c: 'rules', n: 'Difficulty Offset',
    h: 'Scales wild dino levels (0 to 1). With "Override Official Difficulty" set to 5, a value of 1 gives wild dinos up to level 150.' },
  { k: 'OverrideOfficialDifficulty', f: 'gus', t: 'float', d: 0, mn: 0, mx: 10, st: 0.5, c: 'rules', n: 'Override Official Difficulty',
    h: 'Sets the maximum wild dino level: max level = value × 30. Set to 5 for level 150 wild dinos (like official servers). 0 = disabled.' },
  { k: 'bUseSingleplayerSettings', f: 'game', t: 'bool', d: false, c: 'rules', n: 'Use Singleplayer Settings',
    h: 'ON = applies the boosted single-player balance (faster taming, breeding, XP). Good for small private servers that want a casual pace.' },
  { k: 'MaxNumberOfPlayersInTribe', f: 'game', t: 'int', d: 0, c: 'rules', n: 'Max Tribe Size',
    h: 'Maximum players allowed in one tribe. 0 = unlimited. Official "Small Tribes" servers use 6.' },
  { k: 'PreventTribeAlliances', f: 'gus', t: 'bool', d: false, c: 'rules', n: 'Prevent Tribe Alliances',
    h: 'ON = tribes cannot form alliances with each other.' },
  { k: 'MaxAlliancesPerTribe', f: 'game', t: 'int', d: 0, c: 'rules', n: 'Max Alliances per Tribe',
    h: 'How many alliances one tribe can be part of. 0 = no limit.' },
  { k: 'MaxTribesPerAlliance', f: 'game', t: 'int', d: 0, c: 'rules', n: 'Max Tribes per Alliance',
    h: 'How many tribes can join one alliance. 0 = no limit.' },
  { k: 'TribeNameChangeCooldown', f: 'gus', t: 'float', d: 15, c: 'rules', n: 'Tribe Name Change Cooldown (minutes)',
    h: 'How long a tribe must wait between name changes.' },
  { k: 'TribeSlotReuseCooldown', f: 'game', t: 'float', d: 0, c: 'rules', n: 'Tribe Slot Reuse Cooldown (seconds)',
    h: 'After a player leaves a tribe, their slot stays blocked for this many seconds. Used on official Small Tribes to stop "tribe hopping". 0 = off.' },
  { k: 'bPvEAllowTribeWar', f: 'game', t: 'bool', d: true, c: 'rules', n: 'Allow Tribe Wars (PvE)',
    h: 'ON = on PvE servers, two tribes can agree to an official "war" and fight each other for a set time.' },
  { k: 'bPvEAllowTribeWarCancel', f: 'game', t: 'bool', d: false, c: 'rules', n: 'Allow Cancelling Tribe Wars',
    h: 'ON = a tribe war can be cancelled after being agreed but before it starts.' },
  { k: 'bAutoPvETimer', f: 'game', t: 'bool', d: false, c: 'rules', n: 'Auto PvE Timer (PvPvE)',
    h: 'ON = the server automatically switches between PvP and PvE at set times of day. Configure the start/stop times below.' },
  { k: 'AutoPvEStartTimeSeconds', f: 'game', t: 'int', d: 0, c: 'rules', n: 'Auto PvE Start Time (seconds)',
    h: 'When PvE mode turns ON each day, in real-world seconds after midnight (0–86400). Example: 68400 = 7 PM. Needs "Auto PvE Timer" enabled.' },
  { k: 'AutoPvEStopTimeSeconds', f: 'game', t: 'int', d: 0, c: 'rules', n: 'Auto PvE Stop Time (seconds)',
    h: 'When PvE mode turns OFF each day, in real-world seconds after midnight (0–86400). Example: 25200 = 7 AM.' },
  { k: 'bDisableFriendlyFire', f: 'game', t: 'bool', d: false, c: 'rules', n: 'Disable Friendly Fire (PvP)',
    h: 'ON = tribe members cannot damage each other or their own tribe\'s dinos and structures.' },
  { k: 'bPvEDisableFriendlyFire', f: 'game', t: 'bool', d: false, c: 'rules', n: 'Disable Friendly Fire (PvE)',
    h: 'ON = on PvE servers, tribe members cannot hurt their own tribe\'s dinos and structures.' },
  { k: 'PreventDiseases', f: 'gus', t: 'bool', d: false, c: 'rules', n: 'Disable Diseases',
    h: 'ON = diseases (like Swamp Fever) are completely disabled.' },
  { k: 'NonPermanentDiseases', f: 'gus', t: 'bool', d: false, c: 'rules', n: 'Non-Permanent Diseases',
    h: 'ON = diseases are cured by dying/respawning instead of being permanent.' },
  { k: 'ImplantSuicideCD', f: 'gus', t: 'float', d: 28800, c: 'rules', n: 'Implant Suicide Cooldown (seconds)',
    h: 'How long players must wait between using the implant "respawn/suicide" option. Default 28800 = 8 hours.' },

  /* ================= RATES & MULTIPLIERS ================= */
  { k: 'XPMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'XP Multiplier',
    h: 'Overall experience gain. 2 = players and dinos level twice as fast.',
    fx: { t: 'x', exs: [{ base: 20, what: 'XP for a Raptor kill' }, { base: 4, what: 'XP per metal ingot crafted' }] } },
  { k: 'TamingSpeedMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 20, st: 0.1, c: 'rates', n: 'Taming Speed',
    h: 'How fast dinos tame. 5 = five times faster taming.',
    fx: { t: 'time', base: 2100, inv: true, what: 'Taming a level-150 Rex with kibble' } },
  { k: 'HarvestAmountMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Harvest Amount',
    h: 'How many resources you get per hit when gathering wood, stone, meat, etc.',
    fx: { t: 'x', exs: [{ base: 30, what: 'wood per tree swing' }, { base: 500, what: 'stone per farming trip' }] } },
  { k: 'HarvestHealthMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Harvest Health',
    h: 'How much "health" trees/rocks/bodies have before they break. Higher = each node gives more total resources before disappearing.' },
  { k: 'UseOptimizedHarvestingHealth', f: 'gus', t: 'bool', d: false, c: 'rates', n: 'Optimized Harvesting Health',
    h: 'ON = better server performance with high Harvest Amount settings (recommended when Harvest Amount is raised).' },
  { k: 'ClampResourceHarvestDamage', f: 'gus', t: 'bool', d: false, c: 'rates', n: 'Clamp Resource Harvest Damage',
    h: 'ON = limits how much damage dinos do to resource nodes, preventing huge dinos from getting extreme amounts per hit.' },
  { k: 'GenericXPMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Generic XP (passive)',
    h: 'XP gained passively over time ("for being alive").' },
  { k: 'HarvestXPMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Harvesting XP',
    h: 'XP gained from harvesting resources.' },
  { k: 'CraftXPMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Crafting XP',
    h: 'XP gained from crafting items.' },
  { k: 'KillXPMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Kill XP',
    h: 'XP gained from killing creatures and players.' },
  { k: 'SpecialXPMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Special Event XP',
    h: 'XP gained from special sources (e.g. raid boss events).' },
  { k: 'CraftingSkillBonusMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Crafting Skill Bonus',
    h: 'Scales the bonus that the Crafting Skill stat gives to crafted item quality.' },
  { k: 'PlayerHarvestingDamageMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Player Harvesting Damage',
    h: 'How hard players hit resource nodes. Higher = fewer swings per tree/rock.' },
  { k: 'DinoHarvestingDamageMultiplier', f: 'game', t: 'float', d: 3.2, mn: 0, mx: 10, st: 0.1, c: 'rates', n: 'Dino Harvesting Damage',
    h: 'How hard dinos hit resource nodes. Default is 3.2 (dinos already harvest faster than players).' },

  /* ================= PLAYERS & DINO STATS ================= */
  { k: 'PlayerDamageMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Player Damage',
    h: 'Damage players deal. 2 = players hit twice as hard.' },
  { k: 'PlayerResistanceMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Player Resistance',
    h: 'Damage players receive. LOWER = tougher players (0.5 = players take half damage).' },
  { k: 'PlayerCharacterHealthRecoveryMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Player Health Regen',
    h: 'How fast players regenerate health.' },
  { k: 'PlayerCharacterFoodDrainMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Player Food Drain',
    h: 'How fast players get hungry. Lower = food lasts longer.' },
  { k: 'PlayerCharacterWaterDrainMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Player Water Drain',
    h: 'How fast players get thirsty. Lower = water lasts longer.' },
  { k: 'PlayerCharacterStaminaDrainMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Player Stamina Drain',
    h: 'How fast players lose stamina when running/swimming. Lower = more endurance.' },
  { k: 'OxygenSwimSpeedStatMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Oxygen Swim Speed Bonus',
    h: 'How much the Oxygen stat boosts swim speed.' },
  { k: 'MaxFallSpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Max Fall Speed (fall damage)',
    h: 'Scales the falling speed at which players start taking fall damage. Higher = you can fall further without damage.' },
  { k: 'DinoDamageMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Wild Dino Damage',
    h: 'Damage wild dinos deal.' },
  { k: 'DinoResistanceMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Wild Dino Resistance',
    h: 'Damage wild dinos receive. LOWER = tougher wild dinos.' },
  { k: 'TamedDinoDamageMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Tamed Dino Damage',
    h: 'Damage your tamed dinos deal.' },
  { k: 'TamedDinoResistanceMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Tamed Dino Resistance',
    h: 'Damage tamed dinos receive. LOWER = tougher tames.' },
  { k: 'DinoCharacterHealthRecoveryMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Dino Health Regen',
    h: 'How fast dinos regenerate health.' },
  { k: 'DinoCharacterFoodDrainMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Dino Food Drain',
    h: 'How fast dinos get hungry. Also affects taming food consumption.' },
  { k: 'DinoCharacterStaminaDrainMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Dino Stamina Drain',
    h: 'How fast dinos lose stamina. Lower = dinos can run/fly longer.' },
  { k: 'WildDinoCharacterFoodDrainMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Wild Dino Food Drain',
    h: 'How fast WILD dinos get hungry. Higher = starve-taming is faster.' },
  { k: 'WildDinoTorporDrainMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Wild Dino Torpor Drain',
    h: 'How fast knocked-out wild dinos wake up. Lower = they stay unconscious longer (easier taming).' },
  { k: 'TamedDinoCharacterFoodDrainMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Tamed Dino Food Drain',
    h: 'How fast TAMED dinos get hungry.' },
  { k: 'TamedDinoTorporDrainMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Tamed Dino Torpor Drain',
    h: 'How fast tamed dinos lose torpor (wake up).' },
  { k: 'RaidDinoCharacterFoodDrainMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Raid Dino Food Drain (Titanosaur)',
    h: 'How fast "raid dinos" (like the Titanosaur) lose food. Higher = tamed Titanosaurs starve faster.' },
  { k: 'HairGrowthSpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'stats', n: 'Hair Growth Speed',
    h: 'How fast player hair and beards grow.' },

  /* ================= BREEDING & IMPRINTING ================= */
  { k: 'bDisableDinoBreeding', f: 'game', t: 'bool', d: false, c: 'breeding', n: 'Disable Breeding',
    h: 'ON = dinos cannot breed at all.' },
  { k: 'MatingIntervalMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 5, st: 0.05, c: 'breeding', n: 'Mating Interval',
    h: 'Time between matings. LOWER = dinos can mate again sooner (0.5 = half the wait).',
    fx: { t: 'range', lo: 64800, hi: 172800, what: 'Mating cooldown' } },
  { k: 'MatingSpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'breeding', n: 'Mating Speed',
    h: 'How fast the mating process itself completes. Higher = faster.' },
  { k: 'LayEggIntervalMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 5, st: 0.05, c: 'breeding', n: 'Egg Lay Interval',
    h: 'How often egg-laying dinos produce eggs. LOWER = more eggs, more often.' },
  { k: 'EggHatchSpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 50, st: 0.5, c: 'breeding', n: 'Egg Hatch Speed',
    h: 'How fast fertilized eggs hatch (and gestation for live births). 10 = ten times faster.',
    fx: { t: 'time', base: 18000, inv: true, what: 'Hatching a Rex egg' } },
  { k: 'BabyMatureSpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 50, st: 0.5, c: 'breeding', n: 'Baby Mature Speed',
    h: 'How fast babies grow up. 10 = ten times faster.',
    fx: { t: 'time', base: 336000, inv: true, what: 'Raising a baby Rex to adult' } },
  { k: 'BabyFoodConsumptionSpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'breeding', n: 'Baby Food Consumption',
    h: 'How fast babies eat food. Lower = babies need feeding less often.' },
  { k: 'BabyCuddleIntervalMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 5, st: 0.05, c: 'breeding', n: 'Imprint Care Interval',
    h: 'Time between imprint requests (cuddle/walk/food). LOWER = more frequent imprints (0.25 = 4x more often).',
    fx: { t: 'time', base: 28800, what: 'Time between imprint cuddles' } },
  { k: 'BabyCuddleGracePeriodMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'breeding', n: 'Imprint Grace Period',
    h: 'How long you have to do a requested imprint before losing imprint quality. Higher = more forgiving.' },
  { k: 'BabyCuddleLoseImprintQualitySpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'breeding', n: 'Imprint Quality Loss Speed',
    h: 'How fast imprint quality is lost after missing a care request. Lower = less punishing.' },
  { k: 'BabyImprintAmountMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'breeding', n: 'Imprint Amount per Care',
    h: 'How much imprint % each care action gives. Higher = fewer cuddles needed for 100% imprint.' },
  { k: 'BabyImprintingStatScaleMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'breeding', n: 'Imprint Stat Bonus',
    h: 'How strong the stat bonus from imprinting is. 0 = imprinting gives no stat boost.' },
  { k: 'DisableImprintDinoBuff', f: 'gus', t: 'bool', d: false, c: 'breeding', n: 'Disable Rider Imprint Bonus',
    h: 'ON = removes the extra damage/resistance a dino gets when ridden by the player who imprinted it.' },
  { k: 'AllowAnyoneBabyImprintCuddle', f: 'gus', t: 'bool', d: false, c: 'breeding', n: 'Anyone Can Imprint',
    h: 'ON = any player can do imprint care on a baby, not just the person who raised it.' },
  { k: 'PreventMateBoost', f: 'gus', t: 'bool', d: false, c: 'breeding', n: 'Disable Mate Boost',
    h: 'ON = removes the damage/resistance bonus nearby mated pairs give each other.' },

  /* ================= WILD & TAMED DINOS ================= */
  { k: 'DinoCountMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 3, st: 0.05, c: 'dinos', n: 'Wild Dino Count',
    h: 'How many wild dinos spawn on the map. Higher = more dinos (can hurt performance above ~1.5).' },
  { k: 'MaxTamedDinos', f: 'gus', t: 'int', d: 5000, c: 'dinos', n: 'Max Tamed Dinos (server-wide)',
    h: 'Total number of tamed dinos allowed on the whole server before taming is blocked.' },
  { k: 'MaxTamedDinos_SoftTameLimit', f: 'gus', t: 'int', d: 5000, c: 'dinos', n: 'Soft Tame Limit',
    h: 'ASA soft cap: when the server passes this number of tames, the oldest excess tames get a deletion countdown.' },
  { k: 'MaxTamedDinos_SoftTameLimit_CountdownForDeletionDuration', f: 'gus', t: 'int', d: 604800, c: 'dinos', n: 'Soft Limit Deletion Countdown (seconds)',
    h: 'How long dinos over the soft limit survive before being auto-deleted. Default 604800 = 7 days.' },
  { k: 'MaxPersonalTamedDinos', f: 'gus', t: 'int', d: 0, c: 'dinos', n: 'Max Tames per Tribe',
    h: 'Tame cap per tribe/player. 0 = no personal limit. Official servers use 500.' },
  { k: 'bUseTameLimitForStructuresOnly', f: 'game', t: 'bool', d: false, c: 'dinos', n: 'Tame Limit Counts Platforms Only',
    h: 'ON = the personal tame limit only counts platform-saddle dinos and rafts, not normal tames.' },
  { k: 'bDisableDinoTaming', f: 'game', t: 'bool', d: false, c: 'dinos', n: 'Disable Taming',
    h: 'ON = nobody can tame dinos at all.' },
  { k: 'bDisableDinoRiding', f: 'game', t: 'bool', d: false, c: 'dinos', n: 'Disable Riding',
    h: 'ON = nobody can ride dinos.' },
  { k: 'bAllowUnclaimDinos', f: 'game', t: 'bool', d: true, c: 'dinos', n: 'Allow Unclaiming Dinos',
    h: 'ON = players can unclaim their dinos (e.g. to give them to another player).' },
  { k: 'PassiveTameIntervalMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 5, st: 0.05, c: 'dinos', n: 'Passive Tame Feed Interval',
    h: 'Time between feedings for passive tames. LOWER = you can feed again sooner (faster passive taming).' },
  { k: 'PreventDinoTameClassNames', f: 'game', t: 'text', d: '', c: 'dinos', ph: 'Example: Ankylo_Character_BP_C  (one per line)', n: 'Blocked Tame Species',
    h: 'Dino classes that can NEVER be tamed on this server. One class name per line (e.g. Gigant_Character_BP_C blocks Giganotosaurus).',
    pick: { t: 'dino', tpl: '{c}' }},
  { k: 'DestroyTamesOverLevelClamp', f: 'game', t: 'int', d: 0, c: 'dinos', n: 'Destroy Tames Over Level',
    h: 'Tames above this level are deleted on server start. 0 = disabled. Used to remove over-leveled/cheated dinos.' },
  { k: 'bAllowSpeedLeveling', f: 'game', t: 'bool', d: false, c: 'dinos', n: 'Allow Speed Leveling (ground)',
    h: 'ON = players can put level points into Movement Speed on tamed creatures (disabled by default in ASA).' },
  { k: 'bAllowFlyerSpeedLeveling', f: 'game', t: 'bool', d: false, c: 'dinos', n: 'Allow Flyer Speed Leveling',
    h: 'ON = players can level up Movement Speed on flyers (disabled by default, big PvP balance change).' },
  { k: 'AllowFlyerCarryPvE', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Flyers Can Carry (PvE)',
    h: 'ON = flyers can pick up wild dinos and players on PvE servers.' },
  { k: 'AllowFlyingStaminaRecovery', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Flyer Stamina Recovery While Flying',
    h: 'ON = flyers regain stamina while you stand on them (instead of having to land).' },
  { k: 'AllowRaidDinoFeeding', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Allow Feeding Raid Dinos (Titanosaur)',
    h: 'ON = Titanosaurs can be fed and kept permanently instead of starving after taming.' },
  { k: 'DisableDinoDecayPvE', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Disable Dino Decay (PvE)',
    h: 'ON = unattended tamed dinos never auto-unclaim/decay on PvE servers.' },
  { k: 'PvEDinoDecayPeriodMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'dinos', n: 'Dino Decay Time (PvE)',
    h: 'Scales how long tamed dinos last before decaying when owners are offline. Higher = longer.' },
  { k: 'PvPDinoDecay', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Dino Decay (PvP)',
    h: 'ON = dino decay/auto-unclaim is active even with offline raid protection enabled.' },
  { k: 'AutoDestroyDecayedDinos', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Auto-Destroy Decayed Dinos',
    h: 'ON = decayed (unclaimed) dinos are deleted automatically instead of staying claimable.' },
  { k: 'ServerAutoForceRespawnWildDinosInterval', f: 'gus', t: 'float', d: 0, c: 'dinos', n: 'Wild Dino Wipe Interval (seconds)',
    h: 'Automatically destroys and respawns all wild dinos every X seconds (a "dino wipe"). 0 = never. 86400 = daily.' },
  { k: 'PreventSpawnAnimations', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Skip Spawn Animations',
    h: 'ON = players spawn/respawn without the wake-up animation.' },
  { k: 'bUseDinoLevelUpAnimations', f: 'game', t: 'bool', d: true, c: 'dinos', n: 'Dino Level-Up Animation',
    h: 'OFF = tamed dinos skip the little celebration animation when leveled up.' },
  { k: 'EnableCryopodNerf', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Enable Cryopod Sickness Nerf',
    h: 'ON = dinos released from cryopods are temporarily weakened (configure below). Used to limit PvP "cryo armies".' },
  { k: 'CryopodNerfDuration', f: 'gus', t: 'float', d: 10, c: 'dinos', n: 'Cryopod Nerf Duration (seconds)',
    h: 'How long the cryopod release weakness lasts. Needs "Enable Cryopod Sickness Nerf".' },
  { k: 'CryopodNerfDamageMult', f: 'gus', t: 'float', d: 0.01, mn: 0, mx: 1, st: 0.01, c: 'dinos', n: 'Cryopod Nerf: Damage Dealt',
    h: 'Damage multiplier for freshly un-podded dinos (0.01 = they deal only 1% damage during the nerf).' },
  { k: 'CryopodNerfIncomingDamageMultPercent', f: 'gus', t: 'float', d: 0.25, mn: 0, mx: 1, st: 0.01, c: 'dinos', n: 'Cryopod Nerf: Extra Damage Taken',
    h: 'Extra damage taken by freshly un-podded dinos (0.25 = +25% damage taken during the nerf).' },
  { k: 'DisableCryopodEnemyCheck', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Allow Cryopods Near Enemies',
    h: 'ON = cryopods can be used even when enemies are nearby.' },
  { k: 'DisableCryopodFridgeRequirement', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Cryopods Work Without Cryofridge',
    h: 'ON = cryopods do not need a cryofridge to stay charged.' },
  { k: 'AllowCryoFridgeOnSaddle', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Cryofridge on Platform Saddles',
    h: 'ON = cryofridges can be built on platform saddles and rafts.' },
  { k: 'FreezeReaperPregnancy', f: 'gus', t: 'bool', d: false, c: 'dinos', n: 'Freeze Reaper Pregnancy (Aberration)',
    h: 'ON = Reaper pregnancy timer pauses while the player is offline.',
    note: 'Not yet officially confirmed for ASA — test on your server.' },
  { k: 'GlobalCorpseDecompositionTimeMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'dinos', n: 'Corpse Decomposition Time',
    h: 'How long dead bodies stay in the world. Higher = corpses last longer.' },
  { k: 'UseCorpseLifeSpanMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'dinos', n: 'Corpse & Dropped Bag Lifespan',
    h: 'Scales how long corpses and item caches (death bags) stay before disappearing.' },
  { k: 'bUseCorpseLocator', f: 'game', t: 'bool', d: true, c: 'dinos', n: 'Corpse Locator Beam',
    h: 'ON = a green light beam marks where you died so you can find your body.' },
  { k: 'PoopIntervalMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'dinos', n: 'Poop Interval',
    h: 'How often creatures poop. Higher value = more often (more fertilizer).' },

  /* ================= BUILDING & STRUCTURES ================= */
  { k: 'TheMaxStructuresInRange', f: 'gus', t: 'int', d: 10500, c: 'structures', n: 'Max Structures in Range',
    h: 'Maximum structure pieces allowed close together in one area. Raise carefully — very high values hurt performance.' },
  { k: 'StructureDamageMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'structures', n: 'Structure Damage',
    h: 'Damage dealt BY structures (e.g. turrets, spike walls).' },
  { k: 'StructureResistanceMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'structures', n: 'Structure Resistance',
    h: 'Damage taken by structures. LOWER = stronger buildings (0.5 = buildings take half damage).' },
  { k: 'DisableStructureDecayPvE', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Disable Structure Decay (PvE)',
    h: 'ON = buildings never auto-decay on PvE servers, even when owners stop logging in.' },
  { k: 'PvEStructureDecayPeriodMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'structures', n: 'Structure Decay Time (PvE)',
    h: 'Scales how long buildings last before decaying when owners are offline. Higher = longer.' },
  { k: 'PvPStructureDecay', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Structure Decay (PvP)',
    h: 'ON = unattended buildings decay on PvP servers (helps clear abandoned bases).' },
  { k: 'FastDecayUnsnappedCoreStructures', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Fast Decay for Lone Pieces',
    h: 'ON = single unsnapped foundations/pillars (often used to block land) decay much faster — in about 5 days.' },
  { k: 'FastDecayInterval', f: 'game', t: 'int', d: 43200, c: 'structures', n: 'Fast Decay Interval (seconds)',
    h: 'Decay time used for lone pillars/foundations when Fast Decay is on. Default 43200 = 12 hours.' },
  { k: 'OnlyDecayUnsnappedCoreStructures', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Only Lone Pieces Decay',
    h: 'ON = only unsnapped core pieces (lone pillars/foundations) decay; connected bases never do.' },
  { k: 'OnlyAutoDestroyCoreStructures', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Only Auto-Destroy Foundations',
    h: 'ON = auto-destruction only removes foundations/pillars, leaving other decayed pieces alone.' },
  { k: 'AutoDestroyOldStructuresMultiplier', f: 'gus', t: 'float', d: 0, mn: 0, mx: 10, st: 0.1, c: 'structures', n: 'Auto-Destroy Old Structures',
    h: 'ON (set to 1 or higher) = fully decayed structures get demolished automatically. Higher values = they last longer before demolition. 0 = off.' },
  { k: 'StructureDamageRepairCooldown', f: 'game', t: 'int', d: 180, c: 'structures', n: 'Repair Cooldown After Damage (seconds)',
    h: 'How long after taking damage a structure cannot be repaired. 0 = repair instantly any time.' },
  { k: 'ForceAllStructureLocking', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Auto-Lock Everything',
    h: 'ON = all containers and doors are locked by default when placed.' },
  { k: 'AlwaysAllowStructurePickup', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Always Allow Structure Pickup',
    h: 'ON = structures can always be picked up (no 30-second placement window limit).' },
  { k: 'StructurePickupTimeAfterPlacement', f: 'gus', t: 'float', d: 30, c: 'structures', n: 'Pickup Window After Placing (seconds)',
    h: 'How long after placing a piece you can still pick it back up (quick-pickup).' },
  { k: 'StructurePickupHoldDuration', f: 'gus', t: 'float', d: 0.5, mn: 0, mx: 5, st: 0.1, c: 'structures', n: 'Pickup Hold Duration (seconds)',
    h: 'How long you must hold the key to pick up a structure. 0 = instant.' },
  { k: 'AllowIntegratedSPlusStructures', f: 'gus', t: 'bool', d: true, c: 'structures', n: 'S+ Style Structures',
    h: 'OFF = disables the built-in Structures Plus quality-of-life pieces.' },
  { k: 'bDisableStructurePlacementCollision', f: 'game', t: 'bool', d: false, c: 'structures', n: 'Disable Placement Collision',
    h: 'ON = structures can clip into terrain and each other — much more building freedom.' },
  { k: 'AllowCaveBuildingPvE', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Allow Cave Building (PvE)',
    h: 'ON = building inside caves is allowed on PvE servers.' },
  { k: 'AllowCaveBuildingPvP', f: 'gus', t: 'bool', d: true, c: 'structures', n: 'Allow Cave Building (PvP)',
    h: 'OFF = blocks building inside caves on PvP servers.' },
  { k: 'PvEAllowStructuresAtSupplyDrops', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Allow Building at Supply Drops (PvE)',
    h: 'ON = structures can be placed near supply drop locations on PvE.' },
  { k: 'AllowCrateSpawnsOnTopOfStructures', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Crates Can Land on Structures',
    h: 'ON = supply drops can spawn on top of player buildings instead of being blocked by them.' },
  { k: 'EnableExtraStructurePreventionVolumes', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Extra No-Build Zones',
    h: 'ON = blocks building in specific extra areas (like resource-rich zones on The Island).' },
  { k: 'bIgnoreStructuresPreventionVolumes', f: 'game', t: 'bool', d: false, c: 'structures', n: 'Ignore No-Build Zones',
    h: 'ON = allows building in mission areas and other normally blocked zones.' },
  { k: 'IgnoreLimitMaxStructuresInRangeTypeFlag', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Ignore Per-Type Structure Limits',
    h: 'ON = ignores the per-type structure limits (e.g. max number of certain pieces in an area).' },
  { k: 'MaxPlatformSaddleStructureLimit', f: 'gus', t: 'int', d: 0, c: 'structures', n: 'Max Platform Saddles (server-wide)',
    h: 'Total number of platform saddles + rafts allowed on the server. 0 = use game default. Official uses 75.' },
  { k: 'PerPlatformMaxStructuresMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'structures', n: 'Structures per Platform',
    h: 'Scales how many pieces can be built on one platform saddle/raft.' },
  { k: 'PersonalTamedDinosSaddleStructureCost', f: 'gus', t: 'int', d: 0, c: 'structures', n: 'Platform Saddle Tame-Slot Cost',
    h: 'How many tame slots a platform saddle dino costs (e.g. 19 = one platform dino counts as 19 tames). 0 = normal.' },
  { k: 'PlatformSaddleBuildAreaBoundsMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'structures', n: 'Platform Build Area Size',
    h: 'How far structures can extend beyond the edge of a platform saddle. Higher = bigger builds.' },
  { k: 'bAllowPlatformSaddleMultiFloors', f: 'game', t: 'bool', d: false, c: 'structures', n: 'Multiple Floors on Platforms',
    h: 'ON = allows multiple ceiling floors on platform saddles.' },
  { k: 'OverrideStructurePlatformPrevention', f: 'gus', t: 'bool', d: false, c: 'structures', n: 'Allow Turrets on Platforms',
    h: 'ON = turrets and spike structures can be built on platform saddles/rafts (normally blocked).' },
  { k: 'MaxGateFrameOnSaddles', f: 'gus', t: 'int', d: 0, c: 'structures', n: 'Max Gateways on Platforms',
    h: 'How many gateway frames can be placed on a platform saddle. Official uses 2. 0 = no limit set.' },
  { k: 'MaxTrainCars', f: 'gus', t: 'int', d: 8, c: 'structures', n: 'Max Train Cars',
    h: 'Maximum number of train cars that can be linked together (ASA trains).' },
  { k: 'bFlyerPlatformAllowUnalignedDinoBasing', f: 'game', t: 'bool', d: false, c: 'structures', n: 'Dinos Can Stand on Flyer Platforms',
    h: 'ON = non-allied dinos can stand on flying platform saddles (e.g. Quetzal) without sliding off.' },
  { k: 'StructurePreventResourceRadiusMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'structures', n: 'Resource Block Radius Around Buildings',
    h: 'Scales the no-resource-respawn zone around structures. Lower = resources respawn closer to your base.' },

  /* ================= ITEMS & LOOT ================= */
  { k: 'ItemStackSizeMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'items', n: 'Item Stack Size',
    h: 'Scales how many items fit in one stack. 2 = double stack sizes (wood 200 instead of 100).',
    fx: { t: 'x', exs: [{ base: 100, what: 'wood per stack' }, { base: 40, what: 'raw meat per stack' }] } },
  { k: 'GlobalSpoilingTimeMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'items', n: 'Food Spoiling Time',
    h: 'How long food lasts before spoiling. Higher = lasts longer.',
    fx: { t: 'time', base: 600, what: 'Raw meat spoils in' } },
  { k: 'ClampItemSpoilingTimes', f: 'gus', t: 'bool', d: false, c: 'items', n: 'Clamp Spoiling Times',
    h: 'ON = all spoilable items use their normal maximum spoil time (fixes exploits with certain item transfers).' },
  { k: 'GlobalItemDecompositionTimeMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'items', n: 'Dropped Item Despawn Time',
    h: 'How long dropped items stay on the ground. Higher = longer.' },
  { k: 'LimitNonPlayerDroppedItemsCount', f: 'game', t: 'int', d: 0, c: 'items', n: 'Max Auto-Dropped Items in an Area',
    h: 'Limits items dropped by dinos/machines (e.g. poop, eggs) in one area. 0 = no limit. Official uses 600. Helps performance.' },
  { k: 'LimitNonPlayerDroppedItemsRange', f: 'game', t: 'int', d: 0, c: 'items', n: 'Auto-Dropped Items Check Range',
    h: 'The radius (in game units) used by the limit above. Official uses 1600.' },
  { k: 'bDisableLootCrates', f: 'game', t: 'bool', d: false, c: 'items', n: 'Disable Loot Crates',
    h: 'ON = no more supply drops / loot crates spawn.' },
  { k: 'RandomSupplyCratePoints', f: 'gus', t: 'bool', d: false, c: 'items', n: 'Random Crate Locations',
    h: 'ON = supply crates spawn in random locations instead of the fixed known spots.' },
  { k: 'SupplyCrateLootQualityMultiplier', f: 'game', t: 'float', d: 1.0, mn: 1, mx: 5, st: 0.1, c: 'items', n: 'Supply Crate Loot Quality',
    h: 'Better loot in supply drops. Range 1 to 5.' },
  { k: 'FishingLootQualityMultiplier', f: 'game', t: 'float', d: 1.0, mn: 1, mx: 5, st: 0.1, c: 'items', n: 'Fishing Loot Quality',
    h: 'Better loot from fishing. Range 1 to 5.' },
  { k: 'bAllowCustomRecipes', f: 'game', t: 'bool', d: true, c: 'items', n: 'Allow Custom Recipes',
    h: 'OFF = disables the custom cooking recipe system (note pad + cooking pot).' },
  { k: 'CustomRecipeEffectivenessMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'items', n: 'Custom Recipe Effectiveness',
    h: 'How powerful custom recipes are (food/water/health given).' },
  { k: 'CustomRecipeSkillMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'items', n: 'Custom Recipe Skill Effect',
    h: 'How much the Crafting Skill stat improves custom recipes.' },
  { k: 'FuelConsumptionIntervalMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'items', n: 'Fuel Burn Time',
    h: 'How long fuel (gas, wood, sparkpowder) lasts in machines. Higher = burns slower.' },
  { k: 'GlobalPoweredBatteryDurabilityDecreasePerSecond', f: 'game', t: 'float', d: 3.0, mn: 0, mx: 20, st: 0.5, c: 'items', n: 'Battery Drain per Second',
    h: 'How fast batteries drain while powering devices. Lower = batteries last longer.' },
  { k: 'ClampItemStats', f: 'gus', t: 'bool', d: false, c: 'items', n: 'Clamp Item Stats',
    h: 'ON = caps weapon/armor stats to the limits you define in "Item Stat Clamps" (Advanced Overrides). Used to remove over-powered gear.' },
  { k: 'HarvestResourceItemAmountClassMultipliers', f: 'game', t: 'text', d: '', c: 'items',
    ph: '(ClassName="PrimalItemResource_Thatch_C",Multiplier=2.0)', n: 'Per-Resource Harvest Multipliers',
    h: 'Boost or reduce specific resources when harvesting. One entry per line, e.g. make thatch drop double while everything else stays normal.' },

  /* ================= WORLD & ENVIRONMENT ================= */
  { k: 'DayCycleSpeedScale', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'environment', n: 'Day/Night Cycle Speed',
    h: 'How fast a full game day passes. Higher = shorter days AND nights.',
    fx: { t: 'time', base: 2880, inv: true, what: 'A full day+night cycle' } },
  { k: 'DayTimeSpeedScale', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'environment', n: 'Daytime Speed',
    h: 'How fast daytime passes. LOWER = longer days (0.5 = days last twice as long).',
    fx: { t: 'time', base: 2100, inv: true, what: 'Daylight lasts' } },
  { k: 'NightTimeSpeedScale', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'environment', n: 'Nighttime Speed',
    h: 'How fast nighttime passes. HIGHER = shorter nights (2 = nights fly by twice as fast).',
    fx: { t: 'time', base: 780, inv: true, what: 'Night lasts' } },
  { k: 'DisableWeatherFog', f: 'gus', t: 'bool', d: false, c: 'environment', n: 'Disable Fog',
    h: 'ON = disables foggy weather entirely.' },
  { k: 'ResourcesRespawnPeriodMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 5, st: 0.05, c: 'environment', n: 'Resource Respawn Time',
    h: 'How fast trees, rocks and bushes come back. LOWER = faster respawn (0.5 = twice as fast).',
    fx: { t: 'time', base: 300, what: 'Typical bush/rock respawn' } },
  { k: 'ResourceNoReplenishRadiusPlayers', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 5, st: 0.05, c: 'environment', n: 'Resource Block Radius Around Players',
    h: 'Scales how close to players resources can respawn. Lower = resources come back right next to you.' },
  { k: 'ResourceNoReplenishRadiusStructures', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 5, st: 0.05, c: 'environment', n: 'Resource Block Radius Around Structures',
    h: 'Scales how close to buildings resources can respawn. Lower = resources come back closer to bases.' },
  { k: 'CropGrowthSpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'environment', n: 'Crop Growth Speed',
    h: 'How fast crops grow in plots.' },
  { k: 'CropDecaySpeedMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'environment', n: 'Crop Decay Speed',
    h: 'How fast crops wither when not watered/fertilized. Lower = more forgiving.' },

  /* ================= PVP ================= */
  { k: 'PreventOfflinePvP', f: 'gus', t: 'bool', d: false, c: 'pvp', n: 'Offline Raid Protection (ORP)',
    h: 'ON = when a whole tribe is offline, their dinos and structures become protected after the delay below.' },
  { k: 'PreventOfflinePvPInterval', f: 'gus', t: 'float', d: 0, c: 'pvp', n: 'ORP Activation Delay (seconds)',
    h: 'How long after the last tribe member logs off before protection kicks in. Official uses 900 (15 minutes).' },
  { k: 'PreventOfflinePvPConnectionInvincibleInterval', f: 'game', t: 'float', d: 5, c: 'pvp', n: 'ORP Login Invincibility (seconds)',
    h: 'Brief invincibility when logging in on an ORP server, so players are not killed while loading in.' },
  { k: 'bIncreasePvPRespawnInterval', f: 'game', t: 'bool', d: false, c: 'pvp', n: 'Increasing Respawn Timer (anti spawn-rush)',
    h: 'ON = players who die repeatedly in the same area take longer and longer to respawn. Configure below.' },
  { k: 'IncreasePvPRespawnIntervalCheckPeriod', f: 'game', t: 'float', d: 300, c: 'pvp', n: 'Respawn Timer: Check Window (seconds)',
    h: 'Dying again within this window (near the same spot) increases the respawn wait.' },
  { k: 'IncreasePvPRespawnIntervalMultiplier', f: 'game', t: 'float', d: 2, mn: 1, mx: 10, st: 0.5, c: 'pvp', n: 'Respawn Timer: Multiplier',
    h: 'Each repeat death multiplies the wait by this amount.' },
  { k: 'IncreasePvPRespawnIntervalBaseAmount', f: 'game', t: 'float', d: 60, c: 'pvp', n: 'Respawn Timer: Base Wait (seconds)',
    h: 'The starting respawn wait after the first repeat death.' },
  { k: 'DinoTurretDamageMultiplier', f: 'game', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'pvp', n: 'Turret Damage to Dinos',
    h: 'How much damage turrets deal to dinos. Higher = turrets shred attacking dinos faster.' },
  { k: 'bPassiveDefensesDamageRiderlessDinos', f: 'game', t: 'bool', d: false, c: 'pvp', n: 'Spikes Hurt Riderless Dinos',
    h: 'ON = passive defenses (spike walls, plant turrets) damage dinos even with no rider (stops "turret soaking" with unridden dinos).' },
  { k: 'bLimitTurretsInRange', f: 'game', t: 'bool', d: false, c: 'pvp', n: 'Limit Turrets in an Area',
    h: 'ON = caps how many turrets can be active in one area (official uses 100 in a 10k unit radius). Configure below.' },
  { k: 'LimitTurretsRange', f: 'game', t: 'float', d: 10000, c: 'pvp', n: 'Turret Limit Radius (units)',
    h: 'The radius used for the turret limit. 10000 units ≈ 33 foundations.' },
  { k: 'LimitTurretsNum', f: 'game', t: 'int', d: 100, c: 'pvp', n: 'Max Turrets in Radius',
    h: 'Maximum number of active turrets allowed within the radius.' },
  { k: 'bHardLimitTurretsInRange', f: 'game', t: 'bool', d: false, c: 'pvp', n: 'Hard Turret Limit',
    h: 'ON = turrets over the limit cannot even be placed (instead of just being disabled).' },
  { k: 'AllowMultipleAttachedC4', f: 'gus', t: 'bool', d: false, c: 'pvp', n: 'Multiple C4 per Dino',
    h: 'ON = more than one C4 charge can be attached to a single dino.' },
  { k: 'PvPZoneStructureDamageMultiplier', f: 'gus', t: 'float', d: 6.0, mn: 0, mx: 20, st: 0.5, c: 'pvp', n: 'Cave Structure Damage (PvP zones)',
    h: 'Extra damage to structures inside caves/PvP zones on PvE servers. Default 6 = cave structures take 6x damage.',
    note: 'Not yet officially confirmed for ASA — test on your server.' },

  /* ================= CLUSTERS & TRANSFERS ================= */
  { k: 'NoTributeDownloads', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Block ALL Downloads',
    h: 'ON = nothing can be downloaded to this server from obelisks/terminals (no characters, dinos or items in).' },
  { k: 'CrossARKAllowForeignDinoDownloads', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Allow Foreign Dino Downloads',
    h: 'ON = dinos not native to this map can be downloaded (e.g. bring a Wyvern to The Island).' },
  { k: 'PreventDownloadSurvivors', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Block Character Downloads',
    h: 'ON = characters cannot be transferred INTO this server.' },
  { k: 'PreventDownloadItems', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Block Item Downloads',
    h: 'ON = items cannot be transferred INTO this server.' },
  { k: 'PreventDownloadDinos', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Block Dino Downloads',
    h: 'ON = dinos cannot be transferred INTO this server.' },
  { k: 'PreventUploadSurvivors', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Block Character Uploads',
    h: 'ON = characters cannot be uploaded FROM this server.' },
  { k: 'PreventUploadItems', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Block Item Uploads',
    h: 'ON = items cannot be uploaded FROM this server.' },
  { k: 'PreventUploadDinos', f: 'gus', t: 'bool', d: false, c: 'transfers', n: 'Block Dino Uploads',
    h: 'ON = dinos cannot be uploaded FROM this server.' },
  { k: 'MaxTributeItems', f: 'gus', t: 'int', d: 50, c: 'transfers', n: 'Max Uploaded Items',
    h: 'How many items one player can keep in the upload/tribute space at once.' },
  { k: 'MaxTributeDinos', f: 'gus', t: 'int', d: 20, c: 'transfers', n: 'Max Uploaded Dinos',
    h: 'How many dinos one player can keep uploaded at once.' },
  { k: 'TributeItemExpirationSeconds', f: 'gus', t: 'int', d: 86400, c: 'transfers', n: 'Uploaded Item Expiry (seconds)',
    h: 'How long uploaded items last before being deleted. Default 86400 = 24 hours.' },
  { k: 'TributeDinoExpirationSeconds', f: 'gus', t: 'int', d: 86400, c: 'transfers', n: 'Uploaded Dino Expiry (seconds)',
    h: 'How long uploaded dinos last before being deleted. Default 86400 = 24 hours.' },
  { k: 'TributeCharacterExpirationSeconds', f: 'gus', t: 'int', d: 86400, c: 'transfers', n: 'Uploaded Character Expiry (seconds)',
    h: 'How long uploaded characters last before being deleted.' },
  { k: 'MinimumDinoReuploadInterval', f: 'gus', t: 'float', d: 0, c: 'transfers', n: 'Dino Re-Upload Cooldown (seconds)',
    h: 'How long a dino must wait after download before it can be uploaded again. Official uses 43200 (12 hours).' },

  /* ================= CHAT & NOTIFICATIONS ================= */
  { k: 'globalVoiceChat', f: 'gus', t: 'bool', d: false, c: 'chat', n: 'Global Voice Chat',
    h: 'ON = voice chat is heard by everyone on the server, not just nearby players.' },
  { k: 'proximityChat', f: 'gus', t: 'bool', d: false, c: 'chat', n: 'Proximity Text Chat',
    h: 'ON = text chat is only visible to players standing near each other.' },
  { k: 'AlwaysNotifyPlayerLeft', f: 'gus', t: 'bool', d: false, c: 'chat', n: 'Announce When Players Leave',
    h: 'ON = a message is shown whenever a player disconnects.' },
  { k: 'DontAlwaysNotifyPlayerJoined', f: 'gus', t: 'bool', d: false, c: 'chat', n: 'Hide Join Messages',
    h: 'ON = no message is shown when players join the server.' },

  /* ================= HUD & VISUALS ================= */
  { k: 'ServerCrosshair', f: 'gus', t: 'bool', d: true, c: 'hud', n: 'Crosshair',
    h: 'OFF = players get no crosshair (more hardcore aiming).' },
  { k: 'AllowThirdPersonPlayer', f: 'gus', t: 'bool', d: true, c: 'hud', n: 'Third-Person View',
    h: 'OFF = players are locked to first-person view.' },
  { k: 'ShowMapPlayerLocation', f: 'gus', t: 'bool', d: true, c: 'hud', n: 'Show Player on Map',
    h: 'OFF = the map no longer shows your own location (navigation becomes a skill!).' },
  { k: 'ShowFloatingDamageText', f: 'gus', t: 'bool', d: false, c: 'hud', n: 'Floating Damage Numbers',
    h: 'ON = RPG-style damage numbers pop up when you hit things.' },
  { k: 'AllowHitMarkers', f: 'gus', t: 'bool', d: true, c: 'hud', n: 'Hit Markers',
    h: 'OFF = no hit marker indicator for ranged attacks.' },
  { k: 'ServerForceNoHUD', f: 'gus', t: 'bool', d: false, c: 'hud', n: 'Force HUD Off',
    h: 'ON = players get no floating names above dinos/players (immersive/hardcore).' },
  { k: 'EnablePvPGamma', f: 'gus', t: 'bool', d: false, c: 'hud', n: 'Allow Gamma Change (PvP)',
    h: 'ON = players can use the gamma console command on PvP servers (brighten dark nights).' },
  { k: 'DisablePvEGamma', f: 'gus', t: 'bool', d: false, c: 'hud', n: 'Block Gamma Change (PvE)',
    h: 'ON = players can NOT change gamma on PvE servers.' },
  { k: 'bDisablePhotoMode', f: 'game', t: 'bool', d: false, c: 'hud', n: 'Disable Photo Mode',
    h: 'ON = the in-game photo mode is unavailable (sometimes disabled in PvP to prevent scouting).' },

  /* ================= ADMIN, SAVES & LOGS ================= */
  { k: 'SpectatorPassword', f: 'gus', t: 'str', d: '', c: 'admin', n: 'Spectator Password', ph: 'password for spectator access',
    h: 'If set, non-admins can join as spectators using this password.' },
  { k: 'AdminLogging', f: 'gus', t: 'bool', d: false, c: 'admin', n: 'Log Admin Commands to Chat',
    h: 'ON = all admin cheat commands are printed in global chat — keeps admins accountable.' },
  { k: 'RCONEnabled', f: 'gus', t: 'bool', d: false, c: 'admin', n: 'Enable RCON',
    h: 'ON = allows remote admin tools to connect and run commands (needs the Admin Password and the port below).' },
  { k: 'RCONPort', f: 'gus', t: 'int', d: 27020, c: 'admin', n: 'RCON Port',
    h: 'The TCP port for RCON connections. Also forward this port if you use RCON remotely.' },
  { k: 'RCONServerGameLogBuffer', f: 'gus', t: 'float', d: 600, c: 'admin', n: 'RCON Log Buffer (lines)',
    h: 'How many game log lines are kept for RCON "GetGameLog" requests.' },
  { k: 'AutoSavePeriodMinutes', f: 'gus', t: 'float', d: 15, mn: 1, mx: 120, st: 1, c: 'admin', n: 'Auto-Save Interval (minutes)',
    h: 'How often the world is saved automatically. Lower = less progress lost on crash, but brief lag spikes on save.' },
  { k: 'KickIdlePlayersPeriod', f: 'gus', t: 'float', d: 3600, c: 'admin', n: 'Kick Idle Players After (seconds)',
    h: 'AFK players are kicked after this long. Default 3600 = 1 hour. Only works when the server is full-ish.' },
  { k: 'BanListURL', f: 'gus', t: 'str', d: '', c: 'admin', ph: 'http://arkdedicated.com/asabanlist.txt',
    n: 'Shared Ban List URL', h: 'A web address with a list of banned players. Use the official global ban list URL or your own.' },
  { k: 'CustomDynamicConfigUrl', f: 'gus', t: 'str', d: '', c: 'admin', ph: 'https://yoursite.com/dynamicconfig.ini',
    n: 'Dynamic Config URL', h: 'Advanced: a web address the server checks for live setting changes (rates etc.) without restarting. Needs -UseDynamicConfig launch option.' },
  { k: 'CosmeticWhitelistOverride', f: 'gus', t: 'str', d: '', c: 'admin', ph: 'URL to your cosmetic whitelist',
    n: 'Custom Cosmetics Whitelist URL', h: 'Advanced: overrides which player-made cosmetics are allowed on your server.' },
  { k: 'AllowHideDamageSourceFromLogs', f: 'gus', t: 'bool', d: false, c: 'admin', n: 'Allow Hiding Damage Source in Logs',
    h: 'ON = tribe logs can hide who caused damage.' },
  { k: 'TribeLogDestroyedEnemyStructures', f: 'gus', t: 'bool', d: false, c: 'admin', n: 'Log Destroyed Enemy Structures',
    h: 'ON = tribe logs also show enemy structures your tribe destroys (off by default to reduce spam).' },
  { k: 'MaxTribeLogs', f: 'game', t: 'int', d: 400, c: 'admin', n: 'Max Tribe Log Entries',
    h: 'How many log lines each tribe keeps.' },
  { k: 'bShowCreativeMode', f: 'game', t: 'bool', d: false, c: 'admin', n: 'Show Creative Mode',
    h: 'ON = creative mode is available from the pause menu (for building-focused servers).' },
  { k: 'AllowSharedConnections', f: 'gus', t: 'bool', d: false, c: 'admin', n: 'Allow Shared Family Accounts',
    h: 'ON = allows multiple players from the same shared/family game account to join.' },
  { k: 'ListenServerTetherDistanceMultiplier', f: 'gus', t: 'float', d: 1.0, mn: 0, mx: 10, st: 0.1, c: 'admin', n: 'Non-Dedicated Tether Distance',
    h: 'Only for non-dedicated (host & play) sessions: how far other players can move from the host. Ignored on dedicated servers.',
    note: 'Not yet officially confirmed for ASA — test on your server.' },

  /* ================= ENGRAMS & LEVELING ================= */
  { k: 'bAutoUnlockAllEngrams', f: 'game', t: 'bool', d: false, c: 'engrams', n: 'Auto-Unlock All Engrams',
    h: 'ON = every engram unlocks automatically at its required level — no engram points needed.' },
  { k: 'bOnlyAllowSpecifiedEngrams', f: 'game', t: 'bool', d: false, c: 'engrams', n: 'Only Allow Listed Engrams',
    h: 'ON = every engram is hidden/locked except those you explicitly enable in "Engram Overrides" below.' },
  { k: 'bAllowUnlimitedRespecs', f: 'game', t: 'bool', d: false, c: 'engrams', n: 'Unlimited Mindwipes',
    h: 'ON = players can use Mindwipe Tonic (respec) as often as they like, not once per level.' },
  { k: 'OverrideMaxExperiencePointsPlayer', f: 'game', t: 'int', d: 0, c: 'engrams', n: 'Max Player XP Override',
    h: 'Caps total XP players can earn. 0 = default. Only matters with custom level ramps.' },
  { k: 'OverrideMaxExperiencePointsDino', f: 'game', t: 'int', d: 0, c: 'engrams', n: 'Max Dino XP Override',
    h: 'Caps total XP tamed dinos can earn. 0 = default.' },
  { k: 'LevelExperienceRampOverrides', f: 'game', t: 'text', d: '', c: 'engrams',
    ph: '(ExperiencePointsForLevel[0]=5,ExperiencePointsForLevel[1]=20, ... )',
    n: 'Custom Level Ramps', h: 'Fully custom level curves. First line = player levels, second line = dino levels. Use a level calculator website to generate these, then paste here.' },
  { k: 'OverridePlayerLevelEngramPoints', f: 'game', t: 'text', d: '', c: 'engrams',
    ph: '8\n8\n12\n16  (one number per level, in order)',
    n: 'Engram Points per Level', h: 'One line per player level: how many engram points that level grants. Line 1 = level 2, line 2 = level 3, and so on. You need one line for every level.' },
  { k: 'OverrideEngramEntries', f: 'game', t: 'text', d: '', c: 'engrams',
    ph: '(EngramIndex=0,EngramHidden=true)',
    n: 'Engram Overrides (by index)', h: 'Change specific engrams by index: hide them, change point costs or level requirements. One entry per line.' },
  { k: 'OverrideNamedEngramEntries', f: 'game', t: 'text', d: '', c: 'engrams',
    ph: '(EngramClassName="EngramEntry_Campfire_C",EngramHidden=false,EngramPointsCost=3,EngramLevelRequirement=2,RemoveEngramPreReq=false)',
    n: 'Engram Overrides (by name)', h: 'Change specific engrams by class name: hide them, change costs, level requirements or prerequisites. One entry per line. Easier than by-index.',
    pick: { t: 'engram', tpl: '(EngramClassName="{c}",EngramHidden=false,EngramPointsCost=1,EngramLevelRequirement=1,RemoveEngramPreReq=false)' }},
  { k: 'EngramEntryAutoUnlocks', f: 'game', t: 'text', d: '', c: 'engrams',
    ph: '(EngramClassName="EngramEntry_Campfire_C",LevelToAutoUnlock=1)',
    n: 'Auto-Unlock Specific Engrams', h: 'Automatically unlock chosen engrams at a chosen level (e.g. give everyone Tek engrams at level 100). One entry per line.',
    pick: { t: 'engram', tpl: '(EngramClassName="{c}",LevelToAutoUnlock=1)' }},

  /* ================= ADVANCED OVERRIDES ================= */
  { k: 'DinoSpawnWeightMultipliers', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(DinoNameTag=Raptor,SpawnWeightMultiplier=2.0,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=0.25)',
    n: 'Dino Spawn Weights', h: 'Make specific dinos spawn more or less often. One entry per line. Example above doubles Raptor spawn chance but caps them at 25% of an area\'s dinos.',
    pick: { t: 'dino', tpl: '(DinoNameTag={t},SpawnWeightMultiplier=2.0)' }},
  { k: 'NPCReplacements', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(FromClassName="MegaRaptor_Character_BP_C",ToClassName="Dodo_Character_BP_C")',
    n: 'Replace / Remove Dino Species', h: 'Swap one wild species for another, or remove it entirely (leave ToClassName empty to remove). One entry per line.',
    pick: { t: 'dino', tpl: '(FromClassName="{c}",ToClassName="")', hint: 'Pick the dino to replace first — then use 📋 on another dino to copy its class name into ToClassName (leave empty to remove the dino).' }},
  { k: 'ConfigAddNPCSpawnEntriesContainer', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C",NPCSpawnEntries=((AnEntryName="ExtraDodos",EntryWeight=1000.0,NPCsToSpawnStrings=("Dodo_Character_BP_C"))),NPCSpawnLimits=((NPCClassString="Dodo_Character_BP_C",MaxPercentageOfDesiredNumToAllow=0.5)))',
    n: 'Add Dinos to Spawn Areas', h: 'Add extra species to existing spawn areas (e.g. make Wyverns spawn on The Island). One full entry per line. Copy templates from the ARK wiki.'},
  { k: 'ConfigSubtractNPCSpawnEntriesContainer', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C",NPCSpawnEntries=((NPCsToSpawnStrings=("Dodo_Character_BP_C"))))',
    n: 'Remove Dinos from Spawn Areas', h: 'Remove specific species from specific spawn areas. One full entry per line.'},
  { k: 'ConfigOverrideNPCSpawnEntriesContainer', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C", ... )',
    n: 'Fully Replace Spawn Areas', h: 'Completely replace what spawns in an area (advanced). One full entry per line.'},
  { k: 'DinoClassDamageMultipliers', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(ClassName="MegaRex_Character_BP_C",Multiplier=2.0)',
    n: 'Per-Species Wild Damage', h: 'Change damage for specific WILD species only. One entry per line.',
    pick: { t: 'dino', tpl: '(ClassName="{c}",Multiplier=1.5)' }},
  { k: 'DinoClassResistanceMultipliers', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(ClassName="MegaRex_Character_BP_C",Multiplier=0.5)',
    n: 'Per-Species Wild Resistance', h: 'Change damage taken for specific WILD species. Higher multiplier = takes more damage.',
    pick: { t: 'dino', tpl: '(ClassName="{c}",Multiplier=0.5)' }},
  { k: 'TamedDinoClassDamageMultipliers', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(ClassName="Rex_Character_BP_C",Multiplier=1.5)',
    n: 'Per-Species Tamed Damage', h: 'Change damage for specific TAMED species only. One entry per line.',
    pick: { t: 'dino', tpl: '(ClassName="{c}",Multiplier=1.5)' }},
  { k: 'TamedDinoClassResistanceMultipliers', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(ClassName="Rex_Character_BP_C",Multiplier=0.8)',
    n: 'Per-Species Tamed Resistance', h: 'Change damage taken for specific TAMED species. One entry per line.',
    pick: { t: 'dino', tpl: '(ClassName="{c}",Multiplier=0.5)' }},
  { k: 'ConfigOverrideItemCraftingCosts', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(ItemClassString="PrimalItem_WeaponStoneHatchet_C",BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_Wood_C",BaseResourceRequirement=10.0,bCraftingRequireExactResourceType=false)))',
    n: 'Custom Crafting Costs', h: 'Change what items cost to craft. One full entry per line. Copy templates from the ARK wiki.' },
  { k: 'ConfigOverrideItemMaxQuantity', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(ItemClassString="PrimalItemResource_Wood_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))',
    n: 'Per-Item Stack Sizes', h: 'Set exact stack sizes for specific items (overrides the global stack multiplier). One entry per line.' },
  { k: 'ConfigOverrideSupplyCrateItems', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '(SupplyCrateClassString="SupplyCrate_Level03_C",MinItemSets=1,MaxItemSets=1, ... )',
    n: 'Custom Supply Crate Loot', h: 'Fully customize what loot appears in each supply crate type. One full entry per line (they get long — use a beacon editor tool to generate them).' },
  { k: 'ExcludeItemIndices', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: '1234', n: 'Exclude Items (by index)', h: 'Item indices to remove from supply crates. One number per line.' },
  { k: 'PreventBreedingForClassNames', f: 'game', t: 'text', d: '', c: 'advanced',
    ph: 'Gigant_Character_BP_C  (one per line)', n: 'Blocked Breeding Species',
    h: 'Dino classes that cannot be bred. One class name per line.',
    pick: { t: 'dino', tpl: '{c}' }},
  { k: 'ItemStatClamps', f: 'game', t: 'raw', d: '', c: 'advanced',
    ph: 'ItemStatClamps[1]=19800\nItemStatClamps[3]=19800',
    n: 'Item Stat Clamps', h: 'Caps item stats (1=armor, 3=damage %, etc.) — the example caps armor and damage at ~700%. Requires "Clamp Item Stats" (Items & Loot) turned on. Lines are written exactly as typed.' },

  /* ================= CUSTOM ================= */
  { k: '__customGUS', f: 'gus', t: 'raw', d: '', c: 'custom', virtual: true,
    ph: '; Anything here is added to the end of GameUserSettings.ini exactly as written\nSomeSetting=True',
    n: 'Extra Lines → GameUserSettings.ini', h: 'For settings this tool does not have a control for (e.g. mod settings). Lines are appended to GameUserSettings.ini exactly as written. You can include your own [SectionName] headers.' },
  { k: '__customGame', f: 'game', t: 'raw', d: '', c: 'custom', virtual: true,
    ph: '; Anything here is added to the end of Game.ini exactly as written\nSomeModSetting=123',
    n: 'Extra Lines → Game.ini', h: 'Lines are appended to Game.ini exactly as written. Mod configuration sections can go here too.' },
];

/* Per-level stat tables (12 stats each) */
const STAT_GROUPS = [
  { id: 'PerLevelStatsMultiplier_Player', n: 'Player: Stat Gain per Level', c: 'stats',
    h: 'How much each stat point is worth for PLAYERS. Example: set Weight to 2 and every point in Weight gives double capacity.' },
  { id: 'PlayerBaseStatMultipliers', n: 'Player: Starting Stats', c: 'stats',
    h: 'Scales the BASE (level 1) stats of players. Example: 2 in Health = new characters start with 200 HP instead of 100. (Community-documented for ASA; not yet in the official list.)' },
  { id: 'PerLevelStatsMultiplier_DinoWild', n: 'Wild Dinos: Stat Gain per Level', c: 'stats',
    h: 'How much each wild level-up is worth for WILD dinos.' },
  { id: 'PerLevelStatsMultiplier_DinoTamed', n: 'Tamed Dinos: Stat Gain per Level', c: 'stats',
    h: 'How much each level point spent AFTER taming is worth.' },
  { id: 'PerLevelStatsMultiplier_DinoTamed_Add', n: 'Tamed Dinos: Taming Bonus (flat)', c: 'stats',
    h: 'Scales the flat stat bonus dinos get when tamed.' },
  { id: 'PerLevelStatsMultiplier_DinoTamed_Affinity', n: 'Tamed Dinos: Taming Effectiveness Bonus', c: 'stats',
    h: 'Scales the extra stats from high taming effectiveness.' },
];
for (const g of STAT_GROUPS) {
  for (let i = 0; i < 12; i++) {
    OPTIONS.push({
      k: g.id + '[' + i + ']', f: 'game', t: 'float', d: 1.0, c: g.c,
      n: g.n + ' — ' + STAT_NAMES[i], h: g.h, grp: g.id, gi: i, mn: 0, mx: 10, st: 0.1,
    });
  }
}

/* ================= LAUNCH OPTIONS (command line, not INI) ================= */
const MAPS = [
  { id: 'TheIsland_WP',    name: 'The Island' },
  { id: 'TheCenter_WP',    name: 'The Center' },
  { id: 'ScorchedEarth_WP', name: 'Scorched Earth' },
  { id: 'Aberration_WP',   name: 'Aberration' },
  { id: 'Extinction_WP',   name: 'Extinction' },
  { id: 'Ragnarok_WP',     name: 'Ragnarok' },
  { id: 'Astraeos_WP',     name: 'Astraeos' },
  { id: '__custom',        name: 'Custom / Mod Map…' },
];

const LAUNCH_FIELDS = [
  { k: 'map', t: 'map', d: 'TheIsland_WP', n: 'Map', h: 'Which map the server runs. Pick "Custom / Mod Map…" to type a mod map\'s name.' },
  { k: 'customMap', t: 'str', d: '', n: 'Custom Map Name', ph: 'e.g. Svartalfheim_WP', h: 'Only used when Map is set to Custom. Type the map\'s internal name (from the mod page).' },
  { k: 'maxPlayers', t: 'int', d: 70, n: 'Player Slots (-WinLiveMaxPlayers)', h: 'Maximum simultaneous players. ASA sets this on the start command (the old ASE MaxPlayers INI setting does not work in ASA).' },
  { k: 'mods', t: 'str', d: '', ph: 'e.g. 927090,928988', n: 'Extra Mod IDs (-mods)', h: 'Mods you pick in the 🧩 Mods tab are added to -mods automatically. Use this only for extra CurseForge project IDs, comma-separated.' },
  { k: 'platforms', t: 'select', d: '', n: 'Crossplay Platforms (-ServerPlatform)', h: 'Which platforms can join. Leave on "Default" unless you want to restrict.', choices: [
    ['', 'Default (all platforms)'], ['ALL', 'ALL (explicit)'], ['PC', 'PC only'], ['PC+XSX', 'PC + Xbox'], ['PC+PS5', 'PC + PlayStation'], ['XSX+PS5', 'Consoles only'] ] },
  { k: 'battleye', t: 'bool', d: true, n: 'BattlEye Anti-Cheat', h: 'OFF adds -NoBattlEye. Some player communities and mod setups prefer it off; official-style servers keep it on.' },
  { k: 'clusterId', t: 'str', d: '', ph: 'e.g. mycluster123', n: 'Cluster ID (-clusterid)', h: 'Servers with the same cluster ID (and shared cluster folder) allow transfers between each other.' },
  { k: 'clusterDir', t: 'str', d: '', ph: 'e.g. C:\\ASA\\ClusterShared', n: 'Cluster Folder (-ClusterDirOverride)', h: 'A folder shared by all servers in your cluster where uploads are stored.' },
  { k: 'noTransferFromFiltering', t: 'bool', d: false, n: 'Allow Foreign Downloads (-NoTransferFromFiltering)', h: 'ON = allows items/dinos from outside your cluster to be downloaded.' },
  { k: 'exclusiveJoin', t: 'bool', d: false, n: 'Whitelist Only (-exclusivejoin)', h: 'ON = only players on your whitelist (PlayersExclusiveJoinList.txt) can join.' },
  { k: 'forceAllowCaveFlyers', t: 'bool', d: false, n: 'Allow Flyers in Caves (-ForceAllowCaveFlyers)', h: 'ON = flying mounts can enter caves.' },
  { k: 'forceRespawnDinos', t: 'bool', d: false, n: 'Wild Dino Wipe on Start (-ForceRespawnDinos)', h: 'ON = every server start destroys and respawns all wild dinos (fresh spawns after rate changes).' },
  { k: 'noWildBabies', t: 'bool', d: false, n: 'Disable Wild Babies (-NoWildBabies)', h: 'ON = wild baby dinos no longer spawn in the world.' },
  { k: 'disableCustomCosmetics', t: 'bool', d: false, n: 'Disable Custom Cosmetics (-DisableCustomCosmetics)', h: 'ON = player-made cosmetic mods are not shown on your server.' },
  { k: 'useDynamicConfig', t: 'bool', d: false, n: 'Use Dynamic Config (-UseDynamicConfig)', h: 'ON = the server pulls live settings from the Dynamic Config URL (Admin category).' },
  { k: 'serverGameLog', t: 'bool', d: false, n: 'Server Game Log (-servergamelog)', h: 'ON = writes an extended game log (deaths, tames, tribe activity) — useful for admins.' },
  { k: 'activeEvent', t: 'select', d: '', n: 'Active Event (-ActiveEvent)', h: 'Force a seasonal event on. Leave on "None" for normal play.', choices: [
    ['', 'None'], ['Summer', 'Summer Bash'], ['FearEvolved', 'Fear Evolved (Halloween)'], ['TurkeyTrial', 'Turkey Trial (Thanksgiving)'], ['WinterWonderland', 'Winter Wonderland (Christmas)'], ['LoveEvolved', 'Love Evolved (Valentine\'s)'], ['EasterEvent', 'Eggcellent Adventure (Easter)'], ['birthday', 'ARKaeology (Birthday)'] ] },
  { k: 'serverPath', t: 'str', d: '', ph: 'C:\\ASAServer\\ShooterGame\\Binaries\\Win64\\ArkAscendedServer.exe', n: 'Server .exe Location (for the .bat file)', h: 'Where ArkAscendedServer.exe lives on your server machine. Only used when downloading the start .bat file.' },
  { k: 'extraArgs', t: 'str', d: '', ph: 'e.g. -ForceAllowCaveFlyers -port=7777', n: 'Extra Launch Arguments', h: 'Anything extra to append to the command line, exactly as written.' },
];

/* ================= PRESETS ================= */
const PRESETS = [
  {
    id: 'official-pvp', name: 'Official-style PvP',
    desc: 'Close to official PvP servers: 1x rates, level 150 wild dinos, turret limits.',
    values: {
      OverrideOfficialDifficulty: 5, DifficultyOffset: 1, ServerPVE: false,
      MaxPersonalTamedDinos: 500, bLimitTurretsInRange: true,
      bPassiveDefensesDamageRiderlessDinos: true, ServerCrosshair: true,
      ShowMapPlayerLocation: true, AllowThirdPersonPlayer: true,
    },
  },
  {
    id: 'official-pve', name: 'Official-style PvE',
    desc: 'Official PvE feel: 1x rates, level 150 wild dinos, no player damage.',
    values: {
      OverrideOfficialDifficulty: 5, DifficultyOffset: 1, ServerPVE: true,
      MaxPersonalTamedDinos: 500, AllowFlyerCarryPvE: false,
      ServerCrosshair: true, ShowMapPlayerLocation: true,
    },
  },
  {
    id: 'boosted', name: 'Boosted Casual (5x-ish)',
    desc: 'Popular community rates: 5x taming, 3x XP/harvest, 10x hatching & maturing, easy imprints.',
    values: {
      OverrideOfficialDifficulty: 5, DifficultyOffset: 1,
      XPMultiplier: 3, HarvestAmountMultiplier: 3, TamingSpeedMultiplier: 5,
      MatingIntervalMultiplier: 0.5, EggHatchSpeedMultiplier: 10, BabyMatureSpeedMultiplier: 10,
      BabyCuddleIntervalMultiplier: 0.2, BabyImprintAmountMultiplier: 2, BabyFoodConsumptionSpeedMultiplier: 0.5,
      ItemStackSizeMultiplier: 2, 'PerLevelStatsMultiplier_Player[7]': 2,
      AlwaysAllowStructurePickup: true, StructurePickupTimeAfterPlacement: 300,
      DisableCryopodEnemyCheck: true, DisableCryopodFridgeRequirement: true,
      ShowFloatingDamageText: true, EnablePvPGamma: true,
    },
  },
  {
    id: 'smalltribes', name: 'Small Tribes Style',
    desc: 'Official Small Tribes vibe: 6-player tribes, no alliances, 3x rates, faster breeding.',
    values: {
      OverrideOfficialDifficulty: 5, DifficultyOffset: 1, ServerPVE: false,
      MaxNumberOfPlayersInTribe: 6, PreventTribeAlliances: true, TribeSlotReuseCooldown: 86400,
      XPMultiplier: 3, HarvestAmountMultiplier: 3, TamingSpeedMultiplier: 2.5,
      MatingIntervalMultiplier: 0.5, EggHatchSpeedMultiplier: 3, BabyMatureSpeedMultiplier: 3,
      bLimitTurretsInRange: true, bPassiveDefensesDamageRiderlessDinos: true,
    },
  },
  {
    id: 'relaxed', name: 'Relaxed Private Server',
    desc: 'For friends & family: singleplayer balance, forgiving decay, quality-of-life on.',
    values: {
      bUseSingleplayerSettings: true, OverrideOfficialDifficulty: 5, DifficultyOffset: 1,
      ServerPVE: true, DisableStructureDecayPvE: true, DisableDinoDecayPvE: true,
      AlwaysAllowStructurePickup: true, AllowFlyerCarryPvE: true,
      MatingIntervalMultiplier: 0.5, BabyCuddleIntervalMultiplier: 0.25,
      DisableCryopodEnemyCheck: true, DisableCryopodFridgeRequirement: true,
      ShowFloatingDamageText: true, bShowCreativeMode: false, EnablePvPGamma: true,
      KickIdlePlayersPeriod: 0,
    },
  },
];

/* Section order for file generation */
const GUS_SECTION_ORDER = ['SessionSettings', 'ServerSettings', '/Script/Engine.GameSession', 'MessageOfTheDay'];
const GAME_SECTION = '/script/shootergame.shootergamemode';

/* Default section helper */
function optSection(o) {
  if (o.s) return o.s;
  return o.f === 'gus' ? 'ServerSettings' : GAME_SECTION;
}

/* Settings that only exist in the old ARK: Survival Evolved (per the official
   wiki's inASA flags). ASA ignores them — imports keep them in Custom lines
   but warn the user. */
const ASE_ONLY_KEYS = new Set([
  'activemods', 'activemapmod', 'activeeventcolors', 'activetotalconversion',
  'allowedcheatersurl', 'destroyunconnectedwaterpipes', 'mapmodid', 'maxplayers',
  'modids', 'newyearevent', 'preventtransferforclassnames', 'publicipforepic',
  'serverallowansel', 'usevivox', 'maxstructuresinsmallradius', 'radiusstructuresinsmallradius',
]);
